### ISSUE TITLE
Cross compile error

### ISSUE THREAD

**Issue by sdumetz** [pd/apiauth#5]
When cross compiling to windows, I get the following error : 

```
2016/10/27 10:31:21 apiauth: Can not load timezone Etc/GMT: open /usr/local/go\lib\time\zoneinfo.zip: The system cannot find the path specified.
```

With the full panic stack trace below : 

```
panic: apiauth: Can not load timezone Etc/GMT: open /usr/local/go\lib\time\zoneinfo.zip: The system cannot find the path specified.

goroutine 1 [running]:
panic(0x826ee0, 0xc042116ec0)
        /usr/local/go/src/runtime/panic.go:500 +0x1af
log.Panic(0xc042099ec8, 0x2, 0x2)
        /usr/local/go/src/log/log.go:320 +0xd0
vendor/github.com/pd/apiauth.init.1()
        /<PROJECT_DIR>/src/vendor/github.com/pd/apiauth/apiauth.go:19 +0x15f
vendor/github.com/pd/apiauth.init()
        /<PROJECT_DIR>/src/vendor/github.com/pd/apiauth/apiauth.go:189 +0x5d
main.init()
        /<PROJECT_DIR>/<API_AUTH_CREATION
```

I've removed the bits concerning my own code : It does nothing fancy, just `import github.com/pd/apiauth`. The panic doesn't seem to happen in a function call, it's on module loading.

Can't test yet if it's just a cross-compile error or if it happens on every windows build.

**Comment by packrat386** [comment]
Well that's coming from a failure in the call to [time.LoadLocation](https://github.com/pd/apiauth/blob/master/apiauth.go#L17). The [documentation](https://golang.org/pkg/time/#LoadLocation) for that function indicates that this call might fail on non-UNIX systems. It looks like if you can get ahold of a copy of the correct file, you can tell the package where to find it by setting the `ZONEINFO` environment variable.

**Comment by sdumetz** [comment]
Wouldn't it be better to print a warning and continue with a fallback to `time.Local()` for example?

**Comment by packrat386** [comment]
I would certainly be willing to help make that error message easier to understand since right now it just panics, but falling back to `time.Local()` is pretty dangerous. The specification for the [reference implementation](https://github.com/mgomes/api_auth) requires that the timestamp be within a certain window, which means that if you have 2 boxes using different time zones then your requests are all going to get rejected.

**Comment by sdumetz** [comment]
Maybe keep the `panic()` but write a meaningful error message, like : 

```
log.Fatalf("time.LoadLocation(\"Etc/GMT\") failed : %s. Please provide a zoneinfo file using the ZONEINFO env variable",err)
```

Just an example. Any message giving a hint of what is happening without having to look at the source would be enough for users to find and fix it quickly. Maybe a link to `time.LoadLocation()` godoc?
